### ISSUE TITLE
导出pdf有一点点错位

### ISSUE THREAD

**Issue by gitccl** [BillChen2K/typora-theme-next#2]
![image](https://user-images.githubusercontent.com/60637740/81474513-86772300-9238-11ea-98d5-fd7a53c4ed1b.png)
我导出pdf，页面衔接的地方有些字分成两页了，虽然不是很明显:)

**Comment by jtchen2k** [comment]
方便通过邮件提供一下系统版本和 markdown 文件吗？我调整一下。

**Comment by gitccl** [comment]
> 方便通过邮件提供一下系统版本和 markdown 文件吗？我调整一下。

你是指typora的版本吗？

**Comment by jtchen2k** [comment]
> > 方便通过邮件提供一下系统版本和 markdown 文件吗？我调整一下。
> 
> 你是指typora的版本吗？

恩恩，以及系统版本，我在 macOS 下导出似乎没有出现问题。

**Comment by gitccl** [comment]
> > > 方便通过邮件提供一下系统版本和 markdown 文件吗？我调整一下。
> > 
> > 
> > 你是指typora的版本吗？
> 
> 恩恩，以及系统版本，我在 macOS 下导出似乎没有出现问题。

发过去了，你看看

**Comment by jtchen2k** [comment]
应该已经修复了。
