### ISSUE TITLE
Dark theme wanted

### ISSUE THREAD

**Issue by singularitti** [BillChen2K/typora-theme-next#3]
Great theme! Is it possible to publish a dark counterpart? Thank you!

**Comment by jtchen2k** [comment]
Thx I'll do this after my exams.

**Comment by jtchen2k** [comment]
Check out [this release](https://github.com/BillChen2K/typora-theme-next/releases/tag/1.1) and see if there's any issue.

**Comment by singularitti** [comment]
Looks good, thank you!
