### ISSUE TITLE
Jetbrains Mono Ligatures in Code Blocks?

### ISSUE THREAD

**Issue by snak3codes** [BillChen2K/typora-theme-next#4]
How would you get code ligatures inside of code blocks using Next theme?

**Comment by jtchen2k** [comment]
> How would you get code ligatures inside of code blocks using Next theme?

Hi, you can search for `font-variant-ligatures: none;` in next.css. Comment that line and you'll get the ligatures.

**Comment by singularitti** [comment]
Looks good, thank you!

**Comment by snak3codes** [comment]
Thank you! 🙏
